[package]
name = "wgpu_pbr"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/lentille_render",
    "crates/lentille_core",
    "crates/lentille_wgpu_utils",
    "crates/lentille_math",
]

[workspace.dependencies]
rand = "0.8.5"
half = "2.6.0"
bytemuck = { version = "1.19.0", features = ["derive"] }
uuid = { version = "1.11.0", features = ["v4"] }
anyhow = "1.0.92"
env_logger = "0.11"
pollster = "0.4.0"
derive_builder = "0.20.2"
wesl = "0.4.0"

# graphics
winit = { version = "0.30", features = ["rwh_05"] }
wgpu = { version = "24", features = ["naga-ir"] }
naga_oil = "0.17.0"
cgmath = "0.18.0"

# bevy
bevy_ecs = "0.18"
bevy_app = "0.18"
bevy_log = "0.18"
bevy_reflect = "0.18"

[dependencies]
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_log = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
rand = { workspace = true }

color-backtrace = { version = "0.7" }

tiny_bail = "0.4.3"

# egui
egui = "0.31"
egui-wgpu = "0.31"
egui-winit = "0.31"
egui_dock = "0.16"
egui_tiles = "0.12"

# Workspace
lentille_render = { path = "crates/lentille_render" }
lentille_core = { path = "crates/lentille_core" }
lentille_math = { path = "crates/lentille_math" }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
tracing-chrome = "0.7.2"
