[package]
name = "wgpu_pbr"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/lentille_render",
    "crates/lentille_core",
    "crates/lentille_wgpu_utils",
    "crates/lentille_wgpu_macros",
    "crates/lentille_math",
]

[workspace.dependencies]
rand = "0.8.5"
half = "2.6.0"
bytemuck = { version = "1.19.0", features = ["derive"] }
uuid = { version = "1.11.0", features = ["v4"] }
anyhow = "1.0.92"
env_logger = "0.11"
pollster = "0.4.0"
derive_builder = "0.20.2"
wesl = "0.4.0"

# graphics
winit = { version = "0.30", features = ["rwh_06"] }
wgpu = { version = "27", features = ["naga-ir"] }
cgmath = "0.18.0"

# bevy
bevy_ecs = { version = "0.18", features = ["default", "debug"] }
bevy_app = "0.18"
bevy_log = "0.18"
bevy_reflect = "0.18"

[dependencies]
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_log = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
rand = { workspace = true }

color-backtrace = { version = "0.7" }

tiny_bail = "0.4.3"

# iced
iced = { version = "0.14", default-features = false, features = ["wgpu", "thread-pool"] }
iced_wgpu = "0.14"
iced_winit = "0.14"
iced_runtime = "0.14"

# Workspace
lentille_render = { path = "crates/lentille_render" }
lentille_core = { path = "crates/lentille_core" }
lentille_math = { path = "crates/lentille_math" }
lentille_wgpu_utils = { path = "crates/lentille_wgpu_utils" }
lentille_wgpu_macros = { path = "crates/lentille_wgpu_macros" }
bytemuck = { workspace = true }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
tracing-chrome = "0.7.2"
tracing-log = "0.2.0"
wgpu-subscriber = "0.1.0"
